### ISSUE TITLE
Manually disable the components

### ISSUE THREAD

**Issue by bilalafzal01** [checkout/frames-react#18]
How do I manually disable the `CardNumber`, `ExpiryDate` & `Cvv` components? There's no prop defined in the documentation to do so.

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
