### ISSUE TITLE
Error As(framesv2) The card frame does not exist in the DOM.

### ISSUE THREAD

**Issue by maxefi** [checkout/frames-react#25]
hey.

we're facing such an issue in our system with `Frames` implemented:
```
<Frames
        config={createCheckoutComFrameConfig({
          publicKey,
          localization: {
            cardNumberPlaceholder: 'E.g. 1234 5678 9123 4567',
            expiryMonthPlaceholder: `${translate('month')} (MM)`,
            expiryYearPlaceholder: `${translate('year')} (YY)`,
            cvvPlaceholder: 'E.g. 123',
          },
        })}
        cardTokenized={onCardTokenizedHandler}
        frameValidationChanged={onFrameValidationChangedHandler}
        ready={onReadyHandler}
        cardSubmitted={onCardSubmittedHandler}
      >
```

it only happens on mobile devices, it might happen quite randomly and not often.

did somebody face the same issue?

**Comment by Taskim** [comment]
I have the same error

**Comment by crufter** [comment]
I get this too.
Anyone managed to solve this?

**Comment by FrontendFrenzy** [comment]
i get this too, what's the workaround to fix this ?
@checkout is anyone maintaining this pkg ?

**Comment by nqasid** [comment]
Same issue here. I'm guessing no one is maintaining this package, so we won't be getting a fix?

**Comment by arodik** [comment]
Guys, do yoy load the frames script lazily or statically by simply including it into the Head section? We inject the script lazily and have this error, only on iPhones
<img width="325" alt="image" src="https://user-images.githubusercontent.com/2021794/216421311-ee73955d-296a-4042-8dcf-becd113a4841.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/2021794/216421355-f690a03f-087d-411e-8abd-a65ccb3bf628.png">

**Comment by nqasid** [comment]
> Guys, do you load the frames script lazily or statically by simply including it into the Head section? We inject the script lazily and have this error, only on iPhones
> <img alt="image" width="325" src="https://user-images.githubusercontent.com/2021794/216421311-ee73955d-296a-4042-8dcf-becd113a4841.png">
> <img alt="image" width="325" src="https://user-images.githubusercontent.com/2021794/216421355-f690a03f-087d-411e-8abd-a65ccb3bf628.png">

I've tried both ways. I'm on NextJS, so I've loaded the script before anything else on the page loads, and then I tried again, loading the script lazily. Same error.

**Comment by maxefi** [comment]
> Guys, do you load the frames script lazily or statically by simply including it into the Head section? We inject the script lazily and have this error, only on iPhones
<img alt="image" width="325" src="https://user-images.githubusercontent.com/2021794/216421311-ee73955d-296a-4042-8dcf-becd113a4841.png"> <img alt="image" width="325" src="https://user-images.githubusercontent.com/2021794/216421355-f690a03f-087d-411e-8abd-a65ccb3bf628.png">

using it as an npm package, error appears on different variety of devices:
<img width="306" alt="Screenshot 2023-02-16 at 14 02 08" src="https://user-images.githubusercontent.com/14819868/219292420-fb1915b6-8231-4298-90d8-d765d92ff61e.png">
<img width="307" alt="Screenshot 2023-02-16 at 14 02 00" src="https://user-images.githubusercontent.com/14819868/219292433-7e22c2e5-91b2-4e11-b9f8-7cb0e109074d.png">

**Comment by KATT** [comment]
A few observations that I've encountered while integrating this that might help someone:

- You can't reliably mount `<FramesReact/>` immediately on load
- You can't reliably mount `<FramesReact/>` unless the SDK is loaded
- You have to immediately mount `<CardNumber/>` etc **at the same time** as you mount `<FramesReact />`

Something that might help someone:

```tsx
export function CardFormFramesProvider(props: { children: ReactNode }) {
  // Adds the `<script>` tag to the DOM if not already present
  const scriptState = useCardFormScript();

  /**
   * If we don't wait for the component to be mounted before rendering the iframes, it sometimes fails
   * Possibly related: https://github.com/checkout/frames-react/issues/25
   **/
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    setIsMounted(true);
  }, []);
  if (!isMounted) {
    return null;
  }
  if (scriptState === 'loading') {
    return null;
  }
  if (scriptState === 'error') {
    return <div>❌ Something went wrong loading our credit card provider</div>;
  }

  return (
    <FramesReact
      config={{
        // [...]
      }}
    >
      {props.children}
    </FramesReact>
  );
}
```

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
