### ISSUE TITLE
Invalid type for FrameCardTokenizedEvent.name

### ISSUE THREAD

**Issue by rambo14122** [checkout/frames-react#33]
types/types.d.ts
`export interface FrameCardTokenizedEvent {
    type: string;
    token: string;
    expires_on: string;
    expiry_month: string;
    expiry_year: string;
    scheme?: Scheme;
    scheme_local: string;
    last4: string;
    preferred_scheme?: PreferredScheme;
    bin: string;
    card_type?: CardType;
    card_category?: CardCategory;
    issuer?: string;
    issuer_country?: string;
    product_id?: string;
    product_type?: string;
    billing_address?: GatewayBillingAddress;
    phone?: GatewayPhone;
    name?: GatewayBillingAddress;
}`
type for name is incorrect, unable to get card holder name

**Comment by ioan-ghisoi-cko** [comment]
Updated in the latest version.
