### ISSUE TITLE
Autofill CSS passed is not getting applied

### ISSUE THREAD

**Issue by Vaibhav-Dashore** [checkout/frames-react#34]
Hi,

I'm passing the autofill styles to the `style` object like this - 

            <Frames
                    config={
                      {
                        publicKey: checkoutPublicKey,
                        localization: {
                          cardNumberPlaceholder: 'Enter card number',
                          expiryMonthPlaceholder: 'MM ',
                          expiryYearPlaceholder: ' YY',
                          cvvPlaceholder: 'CVV',
                        },
                        style: {
                          base: {
                            // some styles
                          },
                          autofill: {
                            backgroundColor: 'rgba(255,255,255,0.1) !important',
                          },
                          }
                          }}
                          
 Still when the credit card information is auto filled in chrome, a white mask is getting applied over the card field.

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
