### ISSUE TITLE
Frames.enableSubmitForm is not resubmitting the form

### ISSUE THREAD

**Issue by ManalLiaquat** [checkout/frames-react#41]
When calling Frames.enableSubmitForm to resubmit the form `cardTokenized` callback is not called again

```
"frames-react": "^1.1.0",
"next": "12.3.1",
"react": "17.0.2",
"react-dom": "17.0.2",
```

**Comment by kimmikirino** [comment]
Could you share a piece of code? 
Because I used enableSubmitForm and submitCard, and it worked.

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.

For your issue, enableSubmitForm should allow you to call submitCard again.
