### ISSUE TITLE
Is there a way to change the error message? (Card form invalid)

### ISSUE THREAD

**Issue by kimmikirino** [checkout/frames-react#43]
I would like to change the "Card form invalid" error to an especific error when the card number/cvc/expiry is invalid.
Is there a way of doing that, or should I manually add a state and use "frameValidationChanged", for example?

Thank you in advance.

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
