### ISSUE TITLE
Cross error blocks frames origin 

### ISSUE THREAD

**Issue by BariqDev** [checkout/frames-react#50]
when typing card name and other information we got this error in console but the process of payment done successfully could we fix this error ?
![checkout](https://github.com/checkout/frames-react/assets/126456994/e82a2f8f-07f2-4f93-ad64-56230649a9ce)

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
