### ISSUE TITLE
Arabic support for Frames

### ISSUE THREAD

**Issue by jsphkhan** [checkout/frames-react#6]
How can I add Arabic support for Frames? 

I know that I can use placeholders for the field names:
```js
localization: {
              cardNumberPlaceholder: 'Arabic string',
              expiryMonthPlaceholder: 'MM',
              expiryYearPlaceholder: 'YY',
              cvvPlaceholder: 'CVV'
            },
```

But I am not able to change the direction to RTL. Since inside the iFrame the lang is still set to EN-GB (default locale) even though I use Arabic placeholders. So my input fields and their placeholders are not positioned correctly

```js
<html lang="EN-GB">
```

<img width="862" alt="Screen Shot 2021-05-05 at 4 33 55 AM" src="https://user-images.githubusercontent.com/1991609/117085543-2b004800-ad5b-11eb-900d-6137bb97b67a.png">

**Comment by ioan-ghisoi-cko** [comment]
Closing this issue as this package will soon be deprecated. A new version using [Checkout.com Flow](https://www.checkout.com/docs/payments/accept-payments/accept-a-payment-on-your-website/get-started-with-flow) is currently in the works.
