### ISSUE TITLE
Typescript: Allow Frames to be undefined on Window

### ISSUE THREAD

**Issue by ChrisSargent** [checkout/frames-react#60]
Wouldn't it be more accurate for the `Frames` type on `Window` to be  like this?

```ts
declare global {
    interface Window {
        Frames: FramesAppendedProps | undefined;
    }
}
```

https://github.com/checkout/frames-react/blob/282a3258cbeb9ea6c2d00af159e1181dde07f1e1/src/frames/Frames.tsx#L8

**Comment by ioan-ghisoi-cko** [comment]
Updated in the latest version.
