### ISSUE TITLE
No Type Declarations in `dist`

### ISSUE THREAD

**Issue by ChrisSargent** [checkout/frames-react#65]
After the latest release, there are no type declarations being included in the `dist` folder, despite being referenced from the package.json, hence Typescript thinks there are no longer any types for this package.

<img width="906" alt="Screenshot 2024-11-21 at 11 17 57" src="https://github.com/user-attachments/assets/c5b85516-2e9c-4ba7-a60e-01518895df61">

**Comment by ioan-ghisoi-cko** [comment]
Thank you for flagging this. Working on a fix.

**Comment by ioan-ghisoi-cko** [comment]
V1.2.2 adds the type declarations in the build process.
