### ISSUE TITLE
Change cvv input type from text to password 

### ISSUE THREAD

**Issue by in-ceptive** [checkout/frames-react#8]
is it possible to change the CVV input type from text to make it show as a password (****)

**Comment by ioan-ghisoi-cko** [comment]
This is not currently possible. Also, this package is a wrapper of our [Frames](https://www.checkout.com/docs/integrate/frames) product so this logic is not controlled here. If in the future we do support this kind of functionality, this will be added to the Frames project, and this package will in turn follow.
